[AETHER-3546] Making sure the tag used in the models are not duplicated if they are a release tag in the PR acceptance phase

diff --git a/models/devicesim-1.0.x/Makefile b/models/devicesim-1.0.x/Makefile
--- a/models/devicesim-1.0.x/Makefile
+++ b/models/devicesim-1.0.x/Makefile
@@ -12,7 +12,6 @@ VERSION           ?= ${BASE_VERSION}-devicesim-1.0.0
 LATEST_VERSION           ?= ${BASE_VERSION}-devicesim-latest
 GO_TAG ?= models/devicesim-1.0.0/v${BASE_VERSION}
 KIND_CLUSTER_NAME ?= kind
-HAS_CHANGED=$(shell git --no-pager diff HEAD~1 HEAD . | wc -l) # check if the content of this folder is different than the parent commit
 IS_RELEASED_VERSION=$(shell MY_STRING="${BASE_VERSION}"; MY_REGEX='^([0-9]+)\.([0-9]+)\.([0-9]+)$$'; if [[ $$MY_STRING =~ $$MY_REGEX ]]; then echo true; else echo false; fi)
 
 ## Docker labels. Only set ref and commit date if committed
@@ -65,25 +64,27 @@ test: mod-update # @HELP Run the unit tests
 
 repo-tag:
 ifeq ($(IS_RELEASED_VERSION), true)
-ifneq ("$(HAS_CHANGED)", "0 ")
-	NEW_VERSION=${VERSION} ../../build/build-tools/tag-collision-reject
 	git tag ${GO_TAG}
 	git push origin ${GO_TAG}
 else
-	@echo "No changes, nothing to tag"
+	@echo "devicesim-1.0.0: Not a released version, skip tagging"
 endif
+
+check-tag:
+ifeq ($(IS_RELEASED_VERSION), true)
+	@echo "Checking that tag ${GO_TAG} is not already used"
+	@if [ "$(shell git tag | cat | grep ${GO_TAG})" != "" ]; then \
+		echo "ERROR: Duplicate tag: ${GO_TAG}"; \
+		exit 2; \
+	fi
 else
-	@echo "Not a released version, skip tagging"
+	@echo "devicesim-1.0.0: Not a released version, skip tag check"
 endif
 
 
 publish: image repo-tag # @HELP Builds and publish the docker image (available parameters: DOCKER_REPOSITORY, VERSION)
-ifneq ("$(HAS_CHANGED)", "0 ")
 	docker push ${DOCKER_REPOSITORY}devicesim:${VERSION}
 	docker push ${DOCKER_REPOSITORY}devicesim:${LATEST_VERSION}
-else
-	@echo "No changes, nothing to push"
-endif
 
 kind-only: # @HELP Loads the docker image into the kind cluster  (available parameters: KIND_CLUSTER_NAME, DOCKER_REPOSITORY, VERSION)
 	@if [ "`kind get clusters`" = '' ]; then echo "no kind cluster found" && exit 1; fi
